// SPDX-License-Identifier: GPL-2.0
/*
 * odi_gpon_init.c -- odi_gpon_init_apply(), the replay of gpon_init.bin
 * (odi_replay_blob.h, generated by tools/regtrace/mkgponinit.py from a
 * real boot capture -- see odi_gpon_init.h for the serial-number
 * substitution rule). odi_reg_read/odi_reg_write/odi_switch_table_write come from
 * odi_switch_mock.h on the host build (test includes it before this file)
 * and from the kernel MMIO wrappers of the same name under __KERNEL__,
 * exactly like odi_switch_tbl.c/odi_switch_dal.c.
 */
#include "odi_gpon_init.h"
#include "odi_replay_blob.h"
#include "odi_switch_tbl.h"
#include "odi_switch_reg.h"

#ifdef __KERNEL__
#include <linux/string.h>
#else
#include <string.h>
#endif

void odi_gpon_init_apply(const struct odi_replay_blob *table,
			 const uint8_t serial_number[8], const uint8_t password[10])
{
	struct odi_gpon_init_event event;
	const struct odi_gpon_init_event *ev = &event;
	uint32_t i;

	/* password is not yet consumed by any generated entry -- this board
	 * own gponpw step captured zero writes (empty config), so
	 * gpon_init.bin has nothing tagged for it. Accepted as a
	 * parameter anyway so a future capture with a real password only
	 * needs regenerating the table, not a new function signature here.
	 */
	(void)password;

	for (i = 0; i < table->count; i++) {
		odi_replay_blob_gpon_event(table, i, &event);

		if (ev->kind == ODI_GPON_INIT_TABLE) {
			(void)odi_switch_table_write(ev->table, ev->offset, ev->words, ev->n_words);
			continue;
		}

		{
			uint32_t val = ev->value;

			if (ev->sn_word != ODI_GPON_INIT_SN_WORD_NONE) {
				unsigned int b = (ev->sn_word - 1U) * 2U;	/* words 1..4 -> sn bytes 0,2,4,6 */

				val = ((uint32_t)serial_number[b] << 8) | (uint32_t)serial_number[b + 1U];
			}
			odi_reg_write(ev->offset, val);
		}
	}
}
