// SPDX-License-Identifier: GPL-2.0
/*
 * odi_switch_sdkinit.c -- "SDK-init replay": implementation of the entry
 * point declared in odi_switch_sdkinit.h. See that header for the event
 * format (reused from odi_switch_init_modload()'s own struct
 * odi_sw_modload_event) and the mask/verb contract; the event data is
 * /lib/firmware/odi/sdkinit.bin (odi_replay_blob.h, GENERATED by
 * tools/regtrace/mksdkinit.py), loaded per verb and released again.
 *
 * odi_reg_read()/odi_reg_write() come from odi_switch_mock.h on the host
 * build, exactly like odi_switch_tbl.c/odi_switch_dal.c; odi_switch_reg.h
 * is force-included the same way for the real __KERNEL__ build (see this
 * driver's own Makefile).
 */
#include "odi_switch_sdkinit.h"
#include "odi_replay_blob.h"
/*
 * odi_switch_reg.h: odi_reg_read()/odi_reg_write() prototypes, __KERNEL__
 * only -- a no-op on the host build, same as odi_switch.c's own headers;
 * test/odi_switch_mock.h's own static inline definitions (included
 * ahead of this file in the unity-build test .c) cover the host
 * build instead.
 */
#include "odi_switch_reg.h"

#ifdef __KERNEL__
#include <linux/jiffies.h>
#include <linux/errno.h>
#include <linux/string.h>
#include <linux/printk.h>
#define ODI_SDKINIT_LOG(fmt, ...) pr_info("odi_switch: " fmt, ##__VA_ARGS__)
#define ODI_SDKINIT_LOG_ERR(fmt, ...) pr_err("odi_switch: " fmt, ##__VA_ARGS__)
typedef unsigned long odi_sdkinit_clock_t;
static inline odi_sdkinit_clock_t odi_sdkinit_clock(void) { return jiffies; }
static inline unsigned long odi_sdkinit_clock_ms(odi_sdkinit_clock_t start)
{
	return jiffies_to_msecs(jiffies - start);
}

/* SoC-window write ("kind w" in the raw regtrace format, ODI_SW_MODLOAD_SOC
 * here): a raw KSEG1 pointer store, a plain 32-bit store to the
 * captured address. 0xb8xxxxxx is already inside the MIPS KSEG1 window (0xA0000000-
 * 0xBFFFFFFF, unmapped, uncached, identity-mapped to the low 512 MB of
 * physical address space) -- no ioremap is needed OR possible for it, the
 * same reasoning the ramlog console already relies on
 * for its own two DRAM pages. odi_switch_sdkinit_apply() below only ever
 * calls this after odi_switch_sdkinit_soc_allowed() has confirmed the
 * address.
 */
static inline void odi_switch_sdkinit_soc_write(uint32_t addr, uint32_t val)
{
	*(volatile uint32_t *)(unsigned long)addr = val;
}
#else
#include <stdio.h>
#include <errno.h>
#include <time.h>
#include <string.h>
#define ODI_SDKINIT_LOG(fmt, ...) printf("odi_switch: " fmt, ##__VA_ARGS__)
#define ODI_SDKINIT_LOG_ERR(fmt, ...) fprintf(stderr, "odi_switch: " fmt, ##__VA_ARGS__)
typedef clock_t odi_sdkinit_clock_t;
static inline odi_sdkinit_clock_t odi_sdkinit_clock(void) { return clock(); }
static inline unsigned long odi_sdkinit_clock_ms(odi_sdkinit_clock_t start)
{
	return (unsigned long)(((clock() - start) * 1000) / CLOCKS_PER_SEC);
}

/* Host build: there is no real KSEG1 to write to, so this only logs the
 * write (kind 'w', matching the raw regtrace format exactly) into the same
 * write log odi_reg_write() already appends to (odi_switch_mock.h, included
 * ahead of this file in every host unity build) -- so a host test can
 * assert the SoC write happened, and where, the same way it already does
 * for a plain register write.
 */
static inline void odi_switch_sdkinit_soc_write(uint32_t addr, uint32_t val)
{
	if (odi_mock.log_n < ODI_MOCK_LOG_MAX) {
		struct odi_mock_write *e = &odi_mock.log[odi_mock.log_n++];

		e->ns = odi_mock.ns;
		e->kind = 'w';
		e->addr = addr;
		e->val = val;
	}
	odi_mock.ns += 10000;
}
#endif

/* SoC-window write allowlist: the switch-SDK register bus is bounds-checked
 * by odi_switch_mmio_offset_in_bounds() before every access (odi_switch.c),
 * but odi_switch_sdkinit_soc_write() above is a raw pointer store with no
 * such guard -- refusing anything not on this list, rather than trusting
 * whatever mksdkinit.py's own generated data says, is the second half of
 * belt-and-braces: a corrupted or mis-generated capture can only ever hit
 * an address a human has already looked at and named here. Every entry is
 * one this codebase has actually seen and understood:
 */
static const uint32_t odi_switch_sdkinit_soc_allowlist[] = {
	/* SoC IP enable -- bit 5 "Enable PONPBO IP", read 0x10 before, write
	 * 0x30 after on this stick. Without it the very next write into the
	 * PBO block (PONQ_0xf02190, 0x00f02190, part of the `switch` verb's own
	 * replay data) stalls the bus with interrupts off and the
	 * hardware watchdog unable to reset the board -- the sdkinit
	 * replay used to skip this write entirely (it lives on a bus
	 * mksdkinit.py silently excluded), which is exactly the trial f1
	 * wedge this allowlist and the generator fix are both here for.
	 */
	0xb800063cU,
	/* SoC GPIO ABCD block, two registers adjacent to DIR/DATA (0xb8003308/
	 * 0xb800330c, rcS's own "optics" comment) -- a read-then-write-same-value
	 * GPIO-mux keepalive the `gpon` verb's own replay data also carries.
	 */
	0xb8003324U,
	0xb8003328U,
	/* SoC clock/reset enable, board init -- read 0x0000035f, written back
	 * unchanged on this stick reference boot (isp1-260923-g4-boot.txt,
	 * the "== 2.94 boot" window, before rcS ever runs). The capture shows
	 * it as the first board-init SoC write, right before the I2C
	 * enable pair -- CONFIG_ODI_BOARD's own odi_board_init()
	 * (odi_board.c) replays it as the first of that same board's own two SoC
	 * writes, i2c's own pair (0xb8003324/28 above) second, same order the
	 * capture recorded.
	 */
	0xb8000044U,
};

static int odi_switch_sdkinit_soc_allowed(uint32_t addr)
{
	unsigned int i;

	for (i = 0; i < sizeof(odi_switch_sdkinit_soc_allowlist) / sizeof(odi_switch_sdkinit_soc_allowlist[0]); i++)
		if (odi_switch_sdkinit_soc_allowlist[i] == addr)
			return 1;
	return 0;
}

/* Default: every verb this table knows about, replayed. Overridden at
 * boot from /var/config/sdkinit.mask (rootfs/skeleton/etc/init.d/rcS) or
 * by hand via `echo sdkinit_mask <hex> > /proc/odi_omci`
 * (odi_omci.c) -- odi_switch_sdkinit.h has the full contract.
 */
static uint32_t odi_switch_sdkinit_mask_ = ODI_SW_SDKINIT_MASK_ALL;

uint32_t odi_switch_sdkinit_mask_get(void)
{
	return odi_switch_sdkinit_mask_;
}

void odi_switch_sdkinit_mask_set(uint32_t mask)
{
	odi_switch_sdkinit_mask_ = mask;
}

const char *const odi_switch_sdkinit_verb_names[ODI_SDKINIT_VERB_ID_COUNT] = {
	[ODI_SDKINIT_SWITCH] = "switch",
	[ODI_SDKINIT_SVLAN] = "svlan",
	[ODI_SDKINIT_STP] = "stp",
	[ODI_SDKINIT_OAM] = "oam",
	[ODI_SDKINIT_ACL] = "acl",
	[ODI_SDKINIT_QOS] = "qos",
	[ODI_SDKINIT_SEC] = "sec",
	[ODI_SDKINIT_RATE] = "rate",
	[ODI_SDKINIT_CLASSIFY] = "classify",
	[ODI_SDKINIT_STAT] = "stat",
	[ODI_SDKINIT_TRUNK] = "trunk",
	[ODI_SDKINIT_L2] = "l2",
	[ODI_SDKINIT_VLAN] = "vlan",
	[ODI_SDKINIT_PORT] = "port",
	[ODI_SDKINIT_MIRROR] = "mirror",
	[ODI_SDKINIT_CPU] = "cpu",
	[ODI_SDKINIT_RLDP] = "rldp",
	[ODI_SDKINIT_TRAP] = "trap",
	[ODI_SDKINIT_GPIO] = "gpio",
	[ODI_SDKINIT_TIME] = "time",
	[ODI_SDKINIT_PONMAC] = "ponmac",
	[ODI_SDKINIT_I2C] = "i2c",
	[ODI_SDKINIT_I2CEN] = "i2cen",
	[ODI_SDKINIT_GPON] = "gpon",
	[ODI_SDKINIT_RXSD] = "rxsd",
};

static void odi_switch_sdkinit_apply_event(const struct odi_sw_modload_event *e)
{
	if (e->kind == ODI_SW_MODLOAD_REG) {
		/* Read-modify-write with a full mask, per instruction --
		 * arithmetically the same result as a blind write, kept
		 * as a real read+write so the RMW shape matches every
		 * other replay this codebase does (init_platform, parity,
		 * modload).
		 */
		uint32_t reg = odi_reg_read(e->offset);

		reg = (reg & 0U) | e->value;
		odi_reg_write(e->offset, reg);
	} else if (e->kind == ODI_SW_MODLOAD_SOC) {
		/* Allowlisted, and logged when refused (odi_switch_soc_write()). */
		(void)odi_switch_soc_write(e->offset, e->value);
	} else {
		(void)odi_switch_table_write(e->table, e->offset, e->words, e->n_words);
	}
}

/* Records of one verb are contiguous (odi_replay_blob_parse() refuses a
 * blob whose verbs are out of order), so this stops at the first record
 * past the verb.
 */
static unsigned int odi_switch_sdkinit_apply(const struct odi_replay_blob *blob,
					     enum odi_sw_sdkinit_verb_id id)
{
	struct odi_sw_modload_event e;
	unsigned int applied = 0;
	uint32_t i;
	uint8_t verb;

	for (i = 0; i < blob->count; i++) {
		odi_replay_blob_switch_event(blob, i, &e, &verb);
		if (verb < id)
			continue;
		if (verb > id)
			break;
		odi_switch_sdkinit_apply_event(&e);
		applied++;
	}
	return applied;
}

static int odi_switch_sdkinit_verb_is_i2c(unsigned int id)
{
	return id == ODI_SDKINIT_I2C || id == ODI_SDKINIT_I2CEN;
}

int odi_switch_sdkinit_verb(const char *verb)
{
	struct odi_replay_fw fw;
	odi_sdkinit_clock_t start;
	unsigned int id, applied;
	int rc;

	for (id = 0; id < ODI_SDKINIT_VERB_ID_COUNT; id++)
		if (strcmp(odi_switch_sdkinit_verb_names[id], verb) == 0)
			break;
	if (id == ODI_SDKINIT_VERB_ID_COUNT)
		return -ENOENT;

	/* Bit clear: this boot mask asks for this verb to be skipped
	 * (bisection) -- same answer as an unknown verb, without loading
	 * anything or touching hardware.
	 */
	if (!(odi_switch_sdkinit_mask_ & ODI_SW_SDKINIT_ITEM(id)))
		return -ENOENT;

	rc = odi_replay_fw_load(ODI_REPLAY_TABLE_SDKINIT, &fw);
	if (rc)
		return rc;

	/* The caller holds odi_switch_lock (odi_rtk_init.c). The two I2C
	 * bring-up verbs also set up the I2C master a DDM read drives, so
	 * they take odi_i2c_lock as well, inside it (odi_switch.c has the
	 * order).
	 */
	start = odi_sdkinit_clock();
	if (odi_switch_sdkinit_verb_is_i2c(id)) {
		mutex_lock(&odi_i2c_lock);
		applied = odi_switch_sdkinit_apply(&fw.blob, id);
		mutex_unlock(&odi_i2c_lock);
	} else {
		applied = odi_switch_sdkinit_apply(&fw.blob, id);
	}
	odi_replay_fw_release(&fw);

	/* Known to this table, but the reference capture recorded nothing
	 * replayable for it (e.g. `trunk`/`gpio`: a zero-write boot phase,
	 * not a generation gap).
	 */
	if (applied == 0)
		return -ENOENT;

	ODI_SDKINIT_LOG("sdkinit verb %s: %u events applied in %lu ms\n",
			verb, applied, odi_sdkinit_clock_ms(start));
	return 0;
}

int odi_switch_soc_write(uint32_t addr, uint32_t val)
{
	if (!odi_switch_sdkinit_soc_allowed(addr)) {
		ODI_SDKINIT_LOG_ERR(
			"refusing SoC-window write to 0x%08x=0x%08x, not on the allowlist\n",
			addr, val);
		return -EPERM;
	}
	odi_switch_sdkinit_soc_write(addr, val);
	return 0;
}
