/* SPDX-License-Identifier: GPL-2.0 */
/*
 * odi_switch_sdkinit.h -- "SDK-init replay": one ordered event list per
 * rtk_init verb (switch svlan stp oam acl qos sec rate classify stat
 * trunk l2 vlan port mirror cpu rldp trap gpio time ponmac) and per PON
 * step (i2c i2cen gpon rxsd), captured from a clean boot and replayed
 * through the same primitives odi_switch_init_modload() already uses
 * (odi_switch_dal.h, "module-load replay"), instead of calling into the
 * stock switch kernel module for that verb.
 *
 * intr and irq are never covered here: they register software interrupt
 * handlers (a software ISR dispatch table), not switch
 * register/table state -- a later phase (odi_intr) replaces those two,
 * not a data replay.
 *
 * Each event is a struct odi_sw_modload_event (odi_switch_dal.h): a
 * register entry (kind ODI_SW_MODLOAD_REG), a table-row entry (kind
 * ODI_SW_MODLOAD_TABLE) or a SoC-window write (kind ODI_SW_MODLOAD_SOC).
 * The events are not compiled in: they live in /lib/firmware/odi/
 * sdkinit.bin (odi_replay_blob.h has the format; GENERATED by
 * tools/regtrace/mksdkinit.py), one record per event, grouped by verb in
 * the enum order below and in capture order within a verb.
 * odi_switch_sdkinit_verb() loads that file, applies the records of one
 * verb and releases it again. category and reg_group are always 0 here:
 * sdkinit bisection granularity is one verb, via odi_switch_sdkinit_mask
 * below, not a sub-verb category split the way modload category 0 needed.
 */
#ifndef ODI_SWITCH_SDKINIT_H
#define ODI_SWITCH_SDKINIT_H

#include "odi_switch_dal.h" /* struct odi_sw_modload_event, odi_switch_table_write() */

/* Bit-per-verb mask, ONE FIXED ORDER (the /proc/rtk_init verb order,
 * rtk_init verbs first, PON steps after) -- enum index N is
 * mask bit N (ODI_SW_SDKINIT_ITEM(N)), and the verb byte of each
 * sdkinit.bin record. This order does not depend on which verbs the
 * current sdkinit.bin generation actually populated: a verb the capture
 * recorded nothing for still owns its bit, it simply never has data to
 * apply. Never renumber this list without updating
 * tools/regtrace/replayblob.py's own SDKINIT_VERBS (they must stay the same
 * order, index for index), odi_switch_sdkinit_verb_names[] and
 * rootfs/skeleton's own /var/config/sdkinit.mask documentation.
 */
enum odi_sw_sdkinit_verb_id {
	ODI_SDKINIT_SWITCH = 0,
	ODI_SDKINIT_SVLAN,
	ODI_SDKINIT_STP,
	ODI_SDKINIT_OAM,
	ODI_SDKINIT_ACL,
	ODI_SDKINIT_QOS,
	ODI_SDKINIT_SEC,
	ODI_SDKINIT_RATE,
	ODI_SDKINIT_CLASSIFY,
	ODI_SDKINIT_STAT,
	ODI_SDKINIT_TRUNK,
	ODI_SDKINIT_L2,
	ODI_SDKINIT_VLAN,
	ODI_SDKINIT_PORT,
	ODI_SDKINIT_MIRROR,
	ODI_SDKINIT_CPU,
	ODI_SDKINIT_RLDP,
	ODI_SDKINIT_TRAP,
	ODI_SDKINIT_GPIO,
	ODI_SDKINIT_TIME,
	ODI_SDKINIT_PONMAC,
	ODI_SDKINIT_I2C,
	ODI_SDKINIT_I2CEN,
	ODI_SDKINIT_GPON,
	ODI_SDKINIT_RXSD,
	ODI_SDKINIT_VERB_ID_COUNT
};

/* The verb names, indexed by enum odi_sw_sdkinit_verb_id. */
extern const char *const odi_switch_sdkinit_verb_names[ODI_SDKINIT_VERB_ID_COUNT];

#define ODI_SW_SDKINIT_ITEM(n)		(1U << (n))
#define ODI_SW_SDKINIT_MASK_ALL		((1U << ODI_SDKINIT_VERB_ID_COUNT) - 1U)

/* Current replay mask -- default ODI_SW_SDKINIT_MASK_ALL (every verb this
 * table knows replayed), overridable at boot from /var/config/
 * sdkinit.mask (rootfs/skeleton/etc/init.d/rcS, same "read a hex mask
 * before the rtk_init loop, fall back to the compiled default" shape as
 * modload.mask/parity.mask) or by hand via `echo sdkinit_mask <hex> >
 * /proc/odi_omci`.
 */
uint32_t odi_switch_sdkinit_mask_get(void);
void odi_switch_sdkinit_mask_set(uint32_t mask);

/* Looks `verb` up in odi_switch_sdkinit_verb_names[]. Unknown to this
 * table (e.g. intr/irq) or its bit currently clear in the mask: returns
 * -ENOENT without loading anything. Otherwise loads sdkinit.bin
 * (odi_replay_fw_load(), process context: this sleeps), and when the verb
 * has at least one record applies them in order (ODI_SW_MODLOAD_REG
 * through odi_reg_read()/_write(), a read-modify-write with a full mask
 * exactly like odi_switch_init_modload()'s own register apply;
 * ODI_SW_MODLOAD_TABLE through odi_switch_table_write(); ODI_SW_MODLOAD_SOC
 * through the allowlist below), logs one line (verb name, event count,
 * elapsed time), releases the file and returns 0. A verb with no records
 * returns -ENOENT; a missing or invalid sdkinit.bin returns the loader
 * error, already logged, and applies nothing. The /proc/rtk_init dispatch
 * (odi_rtk_init.c) logs -ENOSYS for that verb in every one of those cases,
 * so clearing one verb's own bit is how a boot bisects a regression down to
 * a single verb without touching source.
 */
int odi_switch_sdkinit_verb(const char *verb);

/* odi_switch_soc_write() -- the checked half of odi_switch_sdkinit_apply()
 * own ODI_SW_MODLOAD_SOC branch, exported so a caller outside this file can
 * reuse the SAME allowlist (odi_switch_sdkinit.c's own
 * odi_switch_sdkinit_soc_allowlist[]) rather than keep a second one: today
 * that is odi_board_init() (odi_board.c, CONFIG_ODI_BOARD), replaying the
 * two board-init SoC writes (clock/reset enable 0xb8000044, I2C enable
 * 0xb8003324/28) the same "addr on the allowlist or refused and logged, never
 * a blind store" way sdkinit already does for its own PON-step SoC writes.
 * Returns 0 applied, -EPERM refused (not on the allowlist; logged either way).
 */
int odi_switch_soc_write(uint32_t addr, uint32_t val);

#endif /* ODI_SWITCH_SDKINIT_H */
