// SPDX-License-Identifier: GPL-2.0
/*
 * odi_switch_sdkinit.c -- the SDK-init replay: each odi_init verb and PON
 * step replays its records of /lib/firmware/odi/sdkinit.bin (generated by
 * tools/regtrace/mksdkinit.py; odi_replay_blob.h has the format), loaded
 * per verb and released again. odi_switch_sdkinit.h has the contract.
 *
 * The register accessors are those of odi_switch_reg.h in the kernel and
 * of test/odi_switch_mock.h in the host unity build.
 */
#include "odi_switch_sdkinit.h"
#include "odi_replay.h"
#include "odi_replay_blob.h"
#include "odi_switch_reg.h"

#ifdef __KERNEL__
#include <linux/jiffies.h>
#include <linux/errno.h>
#include <linux/string.h>
#include <linux/printk.h>
#define ODI_SDKINIT_LOG(fmt, ...) pr_info("odi_switch: " fmt, ##__VA_ARGS__)
typedef unsigned long odi_sdkinit_clock_t;
static inline odi_sdkinit_clock_t odi_sdkinit_clock(void) { return jiffies; }
static inline unsigned long odi_sdkinit_clock_ms(odi_sdkinit_clock_t start)
{
	return jiffies_to_msecs(jiffies - start);
}
#else
#include <stdio.h>
#include <errno.h>
#include <time.h>
#include <string.h>
#define ODI_SDKINIT_LOG(fmt, ...) printf("odi_switch: " fmt, ##__VA_ARGS__)
typedef clock_t odi_sdkinit_clock_t;
static inline odi_sdkinit_clock_t odi_sdkinit_clock(void) { return clock(); }
static inline unsigned long odi_sdkinit_clock_ms(odi_sdkinit_clock_t start)
{
	return (unsigned long)(((clock() - start) * 1000) / CLOCKS_PER_SEC);
}
#endif

const char *const odi_switch_sdkinit_verb_names[ODI_SDKINIT_VERB_ID_COUNT] = {
	[ODI_SDKINIT_SWITCH] = "switch",
	[ODI_SDKINIT_SVLAN] = "svlan",
	[ODI_SDKINIT_STP] = "stp",
	[ODI_SDKINIT_OAM] = "oam",
	[ODI_SDKINIT_ACL] = "acl",
	[ODI_SDKINIT_QOS] = "qos",
	[ODI_SDKINIT_SEC] = "sec",
	[ODI_SDKINIT_RATE] = "rate",
	[ODI_SDKINIT_CLASSIFY] = "classify",
	[ODI_SDKINIT_STAT] = "stat",
	[ODI_SDKINIT_TRUNK] = "trunk",
	[ODI_SDKINIT_L2] = "l2",
	[ODI_SDKINIT_VLAN] = "vlan",
	[ODI_SDKINIT_PORT] = "port",
	[ODI_SDKINIT_MIRROR] = "mirror",
	[ODI_SDKINIT_CPU] = "cpu",
	[ODI_SDKINIT_RLDP] = "rldp",
	[ODI_SDKINIT_TRAP] = "trap",
	[ODI_SDKINIT_GPIO] = "gpio",
	[ODI_SDKINIT_TIME] = "time",
	[ODI_SDKINIT_PONMAC] = "ponmac",
	[ODI_SDKINIT_I2C] = "i2c",
	[ODI_SDKINIT_I2CEN] = "i2cen",
	[ODI_SDKINIT_GPON] = "gpon",
	[ODI_SDKINIT_RXSD] = "rxsd",
};

/* Replays the records of one verb: a register record is a full-mask
 * read-modify-write, as in the capture (odi_replay.h).
 */
static unsigned int odi_switch_sdkinit_apply(const struct odi_replay_blob *blob,
					     enum odi_sw_sdkinit_verb_id id)
{
	const struct odi_replay_opts opts = { .rmw = 1, .verb = (int)id };

	return odi_replay_run(blob, &opts);
}

static int odi_switch_sdkinit_verb_is_i2c(unsigned int id)
{
	return id == ODI_SDKINIT_I2C || id == ODI_SDKINIT_I2CEN;
}

int odi_switch_sdkinit_verb(const char *verb)
{
	struct odi_replay_fw fw;
	odi_sdkinit_clock_t start;
	unsigned int id, applied;
	int rc;

	for (id = 0; id < ODI_SDKINIT_VERB_ID_COUNT; id++)
		if (strcmp(odi_switch_sdkinit_verb_names[id], verb) == 0)
			break;
	if (id == ODI_SDKINIT_VERB_ID_COUNT)
		return -ENOENT;

	rc = odi_replay_fw_load(ODI_REPLAY_TABLE_SDKINIT, &fw);
	if (rc)
		return rc;

	/* The caller holds odi_switch_lock (odi_init.c). The two I2C
	 * bring-up verbs also set up the I2C master a DDM read drives, so
	 * they take odi_i2c_lock as well, inside it (odi_switch.c has the
	 * order).
	 */
	start = odi_sdkinit_clock();
	if (odi_switch_sdkinit_verb_is_i2c(id)) {
		mutex_lock(&odi_i2c_lock);
		applied = odi_switch_sdkinit_apply(&fw.blob, id);
		mutex_unlock(&odi_i2c_lock);
	} else {
		applied = odi_switch_sdkinit_apply(&fw.blob, id);
	}
	odi_replay_fw_release(&fw);

	/* Known to this table, but the reference capture recorded nothing
	 * replayable for it (e.g. `trunk`/`gpio`: a zero-write boot phase,
	 * not a generation gap).
	 */
	if (applied == 0)
		return -ENOENT;

	ODI_SDKINIT_LOG("sdkinit verb %s: %u events applied in %lu ms\n",
			verb, applied, odi_sdkinit_clock_ms(start));
	return 0;
}
