"""Split a vendor MIB dump into the entities the ONU creates and the ones the
OLT does, and emit the autonomous set.

`initType` in each plugin's table descriptor is exactly that partition:
initType 0 means the ONU creates the entity itself and the OLT may only get and
set it, initType 1 means the OLT creates it. Every table in a live dump lands on
one side or the other with nothing left over.

The autonomous set is what a MIB upload has to report -- after a MIB reset the
ONU's MIB is not empty, it holds what the ONU built for itself, and that is how
the OLT learns what hardware it is talking to before creating anything.

Input is `omcicli mib get all` from a device. That output is device-specific and
is not kept; only the class and instance ids are, which are topology rather than
identity.

    mib-instances.py <dump> [--c DIR]
"""
import json, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))


def load_model():
    with open(os.path.join(HERE, '..', 'generated', 'omci_mib.json')) as fh:
        m = json.load(fh)
    return {e['table']['name']: e['table'] for e in m if e['table']['classId'] is not None}


def parse(path):
    """Table name -> sorted instance ids. The dump brackets each table name
    between two rows of X, and the daemon's own logging is interleaved with it,
    so the name has to look like an identifier to count."""
    lines = open(path, errors='replace').read().splitlines()
    cur, inst = None, {}
    for i, l in enumerate(lines):
        if l.startswith('XXXXXXXX'):
            nxt = lines[i + 1].strip() if i + 1 < len(lines) else ''
            if re.match(r'^[A-Za-z][A-Za-z0-9 _.]*$', nxt):
                cur = nxt
            continue
        m = re.match(r'\s*EntityI[dD]:\s*(0x)?([0-9a-fA-F]+)\s*$', l)
        if m and cur:
            inst.setdefault(cur, set()).add(int(m.group(2), 16))
    return {k: sorted(v) for k, v in inst.items()}


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        return 2
    model, inst = load_model(), parse(sys.argv[1])
    auto, olt, unknown = [], [], []
    for name, ids in sorted(inst.items()):
        t = model.get(name)
        if t is None:
            unknown.append(name)
        elif t['initType'] == 0:
            auto.append((t['classId'], name, ids))
        else:
            olt.append((t['classId'], name, ids))
    auto.sort()
    olt.sort()
    for label, rows in (('autonomous (the ONU builds these)', auto),
                        ('provisioned (the OLT built these)', olt)):
        print('== %s: %d classes, %d instances' %
              (label, len(rows), sum(len(r[2]) for r in rows)))
        for c, name, ids in rows:
            print('   %-6d %-28s %3d' % (c, name, len(ids)))
    if unknown:
        print('not in the model:', unknown)

    if '--c' in sys.argv:
        out = sys.argv[sys.argv.index('--c') + 1]
        os.makedirs(out, exist_ok=True)
        n = sum(len(r[2]) for r in auto)
        lines = [
            '/* The managed entities this ONU creates for itself.',
            ' *',
            ' * Generated by tools/mib-instances.py from a live `omcicli mib get all`,',
            ' * keeping the classes whose initType is 0 -- the ones the OLT may only get',
            ' * and set. This is what a MIB upload reports after a MIB reset.',
            ' *',
            ' * %d classes, %d instances. Measured on an ODI DFP-34X-2C2; another' % (len(auto), n),
            ' * device of the same model should match, a different model will not.',
            ' */',
            '#include "omci_autonomous.h"',
            '',
            'const struct omci_instance omci_autonomous[] = {',
        ]
        for c, name, ids in auto:
            lines.append('\t/* %s */' % name)
            for i in ids:
                lines.append('\t{ %5d, 0x%04x },' % (c, i))
        lines += ['};', '', 'const unsigned omci_autonomous_count = %d;' % n]
        with open(os.path.join(out, 'omci_autonomous.c'), 'w') as fh:
            fh.write('\n'.join(lines) + '\n')
        with open(os.path.join(out, 'omci_autonomous.h'), 'w') as fh:
            fh.write('#ifndef OMCI_AUTONOMOUS_H\n#define OMCI_AUTONOMOUS_H\n\n'
                     '#include <stdint.h>\n\n'
                     'struct omci_instance {\n\tuint16_t classId;\n\tuint16_t inst;\n};\n\n'
                     'extern const struct omci_instance omci_autonomous[];\n'
                     'extern const unsigned omci_autonomous_count;\n\n#endif\n')
        print('wrote %s/omci_autonomous.[ch]: %d instances' % (out, n))
    return 0


if __name__ == '__main__':
    sys.exit(main())
